### ISSUE TITLE
Raspberry Pi freezes

### ISSUE THREAD

**Issue by HackTechDev** [russb78/pi-mation#1]
Hi,

I follow your instruction to run the application but when I want to take a picture, the raspberry pi freezes I can do anything but a hardware reboot.
How to resolve this problem ?
Thx.

**Comment by russb78** [comment]
Thanks for using Pi-Mation! 

I will look into this ASAP, but my initial thought is that you need to update your Raspberry Pi firmware. I had the same problem during development until I did this. 

In the terminal type:
sudo rpi-update

It will take some time.

Let me know if you've already done this / it didn't work.

I intend to return to Pi-Mation for tweaks and improvements in the coming weeks too.

**Comment by HackTechDev** [comment]
Hi,

I thought I updated the firmware but no... O_o
So it is very important to update the firmware to avoid the error.
I can close the ticket.
